/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package notepad;

import java.awt.Color;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import javax.swing.JOptionPane;
import javax.swing.text.Element;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
/**
 *
 * @author Asus
 */

public class editorPanel extends javax.swing.JPanel {

    /**
     * Creates new form editorPanel
     */
    
    private int textLength=0;
    
    public editorPanel() {
        initComponents();
        setLineNumberUI();
    }
    
    public void setLineNumberUI()
    {
        lines.setBackground(Color.LIGHT_GRAY);
        lines.setEditable(false);
      //  Code to implement line numbers inside the JTextArea
        editorPane.getDocument().addDocumentListener(new DocumentListener() {
        public String getText() {
            int caretPosition = editorPane.getDocument().getLength();
            Element root = editorPane.getDocument().getDefaultRootElement();
            String text = "1" + System.getProperty("line.separator");
               for(int i = 2; i < root.getElementIndex(caretPosition) + 2; i++) {
                  text += i + System.getProperty("line.separator");
               }
            return text;
         }
         @Override
         public void changedUpdate(DocumentEvent de) {
            lines.setText(getText());
         }
         @Override
         public void insertUpdate(DocumentEvent de) {
            lines.setText(getText());
         }
         @Override
         public void removeUpdate(DocumentEvent de) {
            lines.setText(getText());
         }
      });
      jScrollPane1.getViewport().add(editorPane);
      jScrollPane1.setRowHeaderView(lines);
    }
    public int getTextLength()
    {
        return textLength;
    }
    public int getCurrentTextLength()
    {
        return editorPane.getText().length();
    }
    public String getContent()
    {
        String s=editorPane.getText();
        return s;
    }
    public void selectText()
    {
        
        editorPane.selectAll();
        
    }
    public String getSelectedText()
    {
        return editorPane.getSelectedText();
    }
    public void cutText()
    {
        editorPane.cut();
    }
    public void copyText()
    {
        editorPane.copy();
    }
    public void save(String fileName) throws FileNotFoundException
    {
        try
        {
            
            FileOutputStream output= new FileOutputStream(fileName);
            String data=editorPane.getText();
            byte[] array = data.getBytes();
            output.write(array);
            output.close(); 
        }
        catch (Exception e) {
            
            System.out.println(e);
        }
    }
    public void open(File selectedFile)
    {
        try
        {
            FileInputStream in=new FileInputStream(selectedFile);
            byte buf[]=new byte[in.available()];
            in.read(buf);
            editorPane.setText(new String(buf));
            textLength=editorPane.getText().length();
        }	
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,"ERR!!"+e,"ERROR",JOptionPane.ERROR_MESSAGE);
        }
    }
    public void setContent(String data)
    {
        editorPane.setText(data);
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        editorPane = new javax.swing.JEditorPane();
        lines = new javax.swing.JTextArea();

        jScrollPane1.setRowHeaderView(editorPane);
        jScrollPane1.setViewportView(editorPane);

        lines.setColumns(4);
        lines.setRows(5);
        lines.setText("1");
        jScrollPane1.setViewportView(lines);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane editorPane;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea lines;
    // End of variables declaration//GEN-END:variables
}
